### ISSUE TITLE
same seed changed address. loki gone?

### ISSUE THREAD

**Issue by heavenone** [loki-project/loki-offline-wallet-generator#1]
created a wallet using offline wallet generator. now wanted to check balance and the seed gives a different address. so i can not find the coins anymore.

**Comment by Doy-lee** [comment]
Hi,

This is abit hard to test, and the first we've received of this sort of issue. However with preliminary testing, restoring a wallet from a seed generated from the generator gives me the same public key as it was listed in the generator as expected, because there'd be a lot more reports if it didn't. 

The only thing I can think of is rescanning the blockchain from height 0 in the CLI/GUI so that all outputs to the address are recalculated. If that results in nothing, then it's likely a key management step on your side has gone wrong.
